# Generated by Django 3.2.9 on 2021-11-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num_of_sold',
            field=models.IntegerField(default=0),
        ),
    ]
